### ISSUE TITLE
Symbol lookup error

### ISSUE THREAD

**Issue by awa292** [gooofy/py-kaldi-simple#32]
Error: **symbol lookup error: /opt/intel/mkl/lib/intel64/libmkl_vml_avx2.so: undefined symbol: mkl_serv_getenv**
Script: examples/chain_online.py

**Comment by gooofy** [comment]
maybe an issue with your kaldi installation?

**Comment by awa292** [comment]
I don't think so. Cloned the github repository and build it from there. Error persists while making with python2.7. If make is done via python3.5, it throws:

**Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/user/py-kaldi-asr-master/chain.py", line 20, in <module>
    kaldi_model_in = KaldiNNet3OnlineModel (MODELDIR_IN.encode('utf-8'), MODEL_IN.encode('utf-8'), acoustic_scale=1.0, beam=15.0, frame_subsampling_factor=3)
  File "kaldiasr/nnet3.pyx", line 87, in kaldiasr.nnet3.KaldiNNet3OnlineModel.__cinit__
    self.modeldir         = _text(modeldir)
  File "kaldiasr/nnet3.pyx", line 49, in kaldiasr.nnet3._text
    raise TypeError("Could not convert to unicode.")
TypeError: Could not convert to unicode.**

After resolving unicode error python3.5 gave same error: **python3.5: symbol lookup error: /opt/intel/mkl/lib/intel64/libmkl_vml_avx2.so: undefined symbol: mkl_serv_getenv**
