### ISSUE TITLE
RuntimeError

### ISSUE THREAD

**Issue by nadeemp78** [gooofy/py-kaldi-simple#38]
When i ran chain_online.py, getting RuntimeError.
data/e2e_tdnnf loading model...
Traceback (most recent call last):
  File "chain_online.py", line 40, in <module>
    kaldi_model = KaldiNNet3OnlineModel (MODELDIR, MODEL)
  File "kaldiasr/nnet3.pyx", line 134, in kaldiasr.nnet3.KaldiNNet3OnlineModel.__cinit__
    self.model_wrapper = new NNet3OnlineModelWrapper(beam, 
RuntimeError: kaldi::KaldiFatalError

Can anyone help me out in knowing why this error came and how to fix it.

**Comment by MengjieQian** [comment]
Hi, I have the same problem, could you please tell me how did you solve the problem? Thanks.

**Comment by MengjieQian** [comment]
Problem solved. Did not set the path to required files correctly.

**Comment by marvin-nj** [comment]
> Problem solved. Did not set the path to required files correctly.

Hello, dear brother :
I have the same question: I  try  english model sucessful, but chinese model failed.
so could you tell me  some details about you experience , thank you very much

**Comment by svenha** [comment]
Which model are your referring to?

**Comment by marvin-nj** [comment]
> Which model are your referring to?

A 16k chinese model trained by myself ,  accyrately model is  ok, it decode sucessfully in kaldi

**Comment by svenha** [comment]
It seems to be hard or impossible to help you in this case: an unknown model AND no details about the failures. A wild guess about the problem would be pitch features for Chinese that you maybe (?) use and are not used in other languages.

**Comment by marvin-nj** [comment]
> It seems to be hard or impossible to help you in this case: an unknown model AND no details about the failures. A wild guess about the problem would be pitch features for Chinese that you maybe (?) use and are not used in other languages.

Yes,  pitch feature is really need in my chinese model, and i config  the  .cpp and .h files to adapt it,  details here:
![image](https://user-images.githubusercontent.com/20610324/106079178-ae544100-614f-11eb-9428-eaed0e120419.png)
 it Compile sucessful, and run the english model dawnloaded  from  zamia-speech  ok, result is here:
![image](https://user-images.githubusercontent.com/20610324/106079975-325af880-6151-11eb-8751-320d13b48411.png)

but , my chinese model  failed,errors like that :
![image](https://user-images.githubusercontent.com/20610324/106079749-c2e50900-6150-11eb-9f9c-3d380eef3385.png)

so, I don't know how to go on now . please help me, thank you !

**Comment by marvin-nj** [comment]
Yes, pitch feature is really need in my chinese model, and i config the .cpp and .h files to adapt it, details like the bold code below:
NNet3OnlineModelWrapper::NNet3OnlineModelWrapper(BaseFloat    beam,
                                                     int32        max_active,
                                                     int32        min_active,
                                                     BaseFloat    lattice_beam,
                                                     BaseFloat    acoustic_scale,
                                                     int32        frame_subsampling_factor,
                                                     **bool         add_pitch,**
                                                     std::string &word_syms_filename,
                                                     std::string &model_in_filename,
                                                     std::string &fst_in_str,
                                                     std::string &mfcc_config,
                                                     **std::string &online_pitch_config,**
                                                     std::string &ie_conf_filename,
                                                     std::string &align_lex_filename)
**feature_config.online_pitch_config         = online_pitch_config;**
**feature_config.add_pitch                   = add_pitch;**

exactly it  Compile sucessful, and run the english model dawnloaded from zamia-speech ok, result is here:
_models/kaldi-generic-en-16k-1200h-tdnnf-r20190609
****************************************************************
** data/en.wav
** i cannot follow you she said 
** data/models/kaldi-generic-en-16k-1200h-tdnnf-r20190609 likelihood: 2.033688
*****************************************************************_

But , my chinese model failed,errors like that :
_data/models/kaldi-dianhua-cn-8k-2700h-tdnnf-baseline
Traceback (most recent call last):
  File "examples/chain_wavfile3.py", line 44, in <module>
    if decoder.decode_wav_file(WAVFILE):
  File "kaldiasr/nnet3.pyx", line 207, in kaldiasr.nnet3.KaldiNNet3OnlineDecoder.decode_wav_file
    wavf.close()
  File "kaldiasr/nnet3.pyx", line 170, in kaldiasr.nnet3.KaldiNNet3OnlineDecoder.decode
    del self.decoder_wrapper
RuntimeError: kaldi::KaldiFatalError_


so, I don't know how to go on now . please help me, thank you !

**Comment by marvin-nj** [comment]
A more strange thing :  KALDI_LOG can't be output when i set the VERBOSE 1.

**Comment by marvin-nj** [comment]
I fix it after reinstall my kaldiasr, everything is ok now , thank you !
